var obj =[
    {list: 1, abb: 'AC', translation: 'Affinity Chromatography', paraphrase: '亲和层析', definition: '亲和色谱也称为亲和层析，是一种利用固定相的结合特性来分离分子的色谱方法。亲和色谱在凝胶过滤色谱柱上连接与待分离的物质有一定结合能力的分子，并且它们的结合是可逆的，在改变流动相条件时二者还能相互分离。亲和色谱可以用来从混合物中纯化或浓缩某一分子，也可以用来去除或减少混合物中某一分子的含量。', color: '#9999CC'},
    {list: 2, abb: 'AD', translation: 'Assembly Drawings', paraphrase: '装配图', definition: '-', color: '#CCCC33'},
    {list: 3, abb: 'ADF', translation: 'Adsorption Depth Filtration', paraphrase: '吸附深层过滤', definition: '-', color: '#CCCC00'},
    {list: 4, abb: 'ADR', translation: 'Adverse Drug Reaction', paraphrase: '药物不良反应', definition: '-', color: '#FFFF00'},
    {list: 5, abb: 'AE', translation: 'Adverse Event', paraphrase: '不良事件', definition: '-', color: '#009966'},
    {list: 6, abb: 'AEX', translation: 'Anion Exchange Chromatography', paraphrase: '阴离子交换层析 ', definition: '一种含阴离子交换剂的层析系统，根据样品混合物中各成分所含负电荷数量的不同，从而对阴离子交换剂结合的强度不同而得以分离。', color: '#009966'},
    {list: 7, abb: 'AI', translation: 'Analog Input', paraphrase: '模拟量输入', definition: '模拟量输入是指输入为连续变化的物理量，相对于数字量(简单的来说就是"0"1"和电流电压两种激活输入单元的方式不同而已)输入（digital input）而言。通俗点其实就是精度，位数越高，把这个模拟量化的越细，结果也就越精准。', color: '#CC99CC'},
    {list: 8, abb: 'AIS', translation: 'Automated Information System', paraphrase: '自动化信息系统', definition: '-', color: '#CCFFCC'},
    {list: 9, abb: 'ANDA', translation: 'Abbreviated New Drug Application', paraphrase: '仿制药申请', definition: 'ANDA的申请即为“复制”一个已被批准上市的产品。其中，这里的“复制”是指其与该上市药品具有相同的活性成分、剂型、规格、服用方式及适应症等。仿制药申请被称为简短的 (abbreviated)，是因为这类申请不需要提供临床前（动物）和临床（人体）数据来证明其安全性和有效性。取而代之的是，仿制药申请者必需提供产品生物等效性的证明材料（比如与原研药相比没有区别）。一旦此类药品获得批准，申请者可以生产并上市这一安全有效且价格低廉的替代物。', color: '#FF9966'},
    {list: 10, abb: 'AO', translation: 'Analog Output', paraphrase: '模拟量输出', definition: '计算机或控制系统输出的模拟量称为模拟量输出，在单片机控制系统中，输出信号中模拟量为数不少，它们是单片机输出的数字信号经过模拟量输出通道处理后得到的。模拟量输出通道的任务是把计算机处理后的数字量信号先通过数据总线、隔离装置，再通过D/A转换器转换成模拟电压或电流信号，经放大用以驱动相应的执行器，从而达到控制的目的。', color: '#FFFF99'},
    {list: 11, abb: 'APS', translation: 'Aseptic Process Simulation', paraphrase: '无菌工艺模拟实验', definition: '-', color: '#FF9933'},
    {list: 12, abb: 'AR', translation: 'Analytic Reagent', paraphrase: '分析纯', definition: '-', color: '#009966'},
    {list: 13, abb: 'AS', translation: 'Asymmetry/Analytical Science', paraphrase: '不对称性/产品开发', definition: '-', color: '#FF9966'},
    {list: 14, abb: 'ASME', translation: 'American Society Of Mechanical Engineers', paraphrase: '美国机械工程师协会', definition: '美国机械工程师协会 (ASME)（American Society of Mechanical Engineers）成立于1880年。现今已成为一家拥有全球超过125,000会员的国际性非盈利教育和技术组织。由于工程领域各学科间交叉性不断增长，ASME出版物也相应提供了跨学科前沿科技的资讯。涵盖的学科内容包括：基础工程、制造、系统设计等方面。', color: '#FFFF99'},
    {list: 15, abb: 'ASTM', translation: 'American Society Of Testing And Materials', paraphrase: '美国测试和材料学会', definition: '-', color: '#9999CC'},
    {list: 16, abb: 'BES', translation: 'Batch Execution Station', paraphrase: '控制站', definition: '固定在同一面板或位于同一外壳中一个或多个控制操动器的集合。', color: '#FF9966'},
    {list: 17, abb: 'BI', translation: 'Biological Indicator', paraphrase: '生物指示物', definition: '生物指示物，是指能通过典型症状或可衡量的反应揭示污染物存在与否的生物体或生物反应。通常选择生态系统中较敏感和快速地对环境污染物产生明显反应的动物、植物或微生物作为指示生物。指示生物通常具有以下基本特征：对污染物反应敏感，有着“预警”的功能；具有代表性，是常见物种，最好是群落中的优势种；对污染物的反应在个体间的差异小、重现性髙。用作指示生物的植物，最好选用无性植物。\n生物指示物可以概括为三类：第一类是根据污染物对该物种造成形态或生理伤害的程度判断污染状况；第二类是根据某个敏感物种出现或消失的概率判断污染状况；第三类是动物或植物对污染物有生物累积作用，可以通过分析其体内污染物的含量判断污染状况。一般说来，指示生物应具备下列条件：生活地点相对固定；产量丰富；容易得到；地理分布广泛；能同时积累几种特殊的污染物质；体内污染物质与外界环境的周转率低，能长时间地把污染物质保留在体内。', color: '#FFCC99'},
    {list: 18, abb: 'BLA', translation: 'Biologics License Application', paraphrase: '生物制品许可申请', definition: '-', color: '#CCCCCC'},
    {list: 19, abb: 'BOM', translation: 'Bill Of Materials', paraphrase: '材料清单', definition: '材料清单（Bill of Material）指的是制造产品所需的所有零件、材料的总清单。', color: '#CC99CC'},
    {list: 20, abb: 'BPDR', translation: 'Biological Product Deviation Report', paraphrase: '生物产品偏差报告', definition: '-', color: '#CCFFFF'},
    {list: 21, abb: 'BPE', translation: 'Bioprocessing Equipment (Bpe) Standard', paraphrase: '生物处理设备（BPE）标准', definition: 'ASME BPE标准规定了需要进行清洁、消毒和/或灭菌的系统和部件的要求，包括在位清洗（CIP\'d）和在线灭菌（SIP\'d）和其它合适工艺的系统。本标准还规定了一次性系统和组件的要求。美国机械工程师协会（ASME）生物处理设备标准的制定是为了帮助设计和建造新的流体处理设备，这些设备用于需要规定纯度和生物负载控制水平的行业。', color: '#FFCC99'},
    {list: 22, abb: 'BPR', translation: 'Batch Production Record', paraphrase: '批生产记录', definition: '-', color: '#6699CC'},
    {list: 23, abb: 'BSC', translation: 'Biological Safety Cabin', paraphrase: '生物安全柜', definition: '-', color: '#FFFF00'},
    {list: 24, abb: 'CA', translation: 'Clean Compressed Air', paraphrase: '洁净压缩空气', definition: '-', color: '#FFCC99'},
    {list: 25, abb: 'CAL', translation: 'Calibration', paraphrase: '校准', definition: '在规定条件下，为确定计量器具示值误差的一组操作。是在规定条件下，为确定计量仪器或测量系统的示值，或实物量具或标准物质所代表的值，与相对应的被测量的已知值之间关系的一组操作。校准结果可用以评定计量仪器、测量系统或实物量具的示值误差，或给任何标尺上的标记赋值。', color: '#33CC99'},
    {list: 26, abb: 'CAPA', translation: 'Corrective and Preventive Action', paraphrase: '纠正和预防措施', definition: '纠正措施：消除已发现的不合格或其他不期望情况的原因所采取的措施；\n预防措施：为消除潜在的不合格或其他潜在不期望情况的原因所采取的措施。', color: '#CCFFFF'},
    {list: 27, abb: 'CCA', translation: 'Component Criticality Assessment', paraphrase: '部件关键性评估', definition: '`风险管理与验证（确认）中的一种手段，通过对“直接影响系统”的关键性部件进行风险评估，确定其在整个系统中的风险程度，并建议控制措施降低其风险，通过评估，最终归“关键性”与“非关键性”两大类。', color: '#CCFF00'},
    {list: 28, abb: 'CCPD', translation: 'Cell Culture Process Development', paraphrase: '细胞培养工艺开发部门', definition: '-', color: '#CC9999'},
    {list: 29, abb: 'CCS', translation: 'Contamination Control Strategy', paraphrase: '污染控制策略', definition: '-', color: '#FF9933'},
    {list: 30, abb: 'CDE', translation: 'Center For Drug Evaluation', paraphrase: '国家药品评审中心', definition: '-', color: '#009999'},
    {list: 31, abb: 'CDER', translation: 'Fda Center For Drug Evaluation And Research', paraphrase: '(美国)FDA药品评价与研究中心', definition: '-', color: '#FF9966'},
    {list: 32, abb: 'CE-SDS', translation: 'Capillary Electrophoresis Sodium Dodecyl Sulfate', paraphrase: '十二烷基硫酸钠毛细管电泳', definition: '以弹性石英毛细管为分离通道，以高压直流电场为驱动力，依据样品中各组分之间淌度和分配行为上的差异而实现分离的电泳分离分析方法。', color: '#6699CC'},
    {list: 33, abb: 'CEX', translation: 'Cation Exchange Chromatography', paraphrase: '阳离子交换层析 ', definition: '离子交换层析中，基质是由带有电荷的树脂或纤维素组成。带有正电荷的称之阴离子交换树脂；而带有负电荷的称之阳离子树脂。离子交换层析同样可以用于蛋白质的分离纯化。由于蛋白质也有等电点，当蛋白质处于不同的pH条件下，其带电状况也不同。阴离子交换基质结合带有负电荷的蛋白质，所以这类蛋白质被留在柱子上，然后通过提高洗脱液中的盐浓度等措施，将吸附在柱子上的蛋白质洗脱下来。结合较弱的蛋白质首先被洗脱下来。反之阳离子交换基质结合带有正电荷的蛋白质，结合的蛋白可以通过逐步增加洗脱液中的盐浓度或是提高洗脱液的pH值洗脱下来。', color: '#33CC99'},
    {list: 34, abb: 'CEX-HPLC', translation: 'Cation Exchange Chromatography-High-Performance Liquid Chromatography', paraphrase: '阳离子交换高效液相色谱', definition: '-', color: '#FFFF99'},
    {list: 35, abb: 'CF', translation: 'Clarification Filtration', paraphrase: '澄清过滤 ', definition: '澄清过滤也可称为深层过滤。使用具有较深通道毛细孔的多空物质，如沙滤棒等过滤介质实现透过式分离方法，过滤中基本不形成滤饼。另外也可以是指借助于重力或离心力产生沉降分层后，实现悬浮物的去除的分离方法。', color: '#CC9999'},
    {list: 36, abb: 'CFR', translation: 'Code of Federal Regulations', paraphrase: '联邦法规', definition: '《美国联邦法规》(Code of Federal Regulations，简称CFR）是美国联邦政府执行机构和部门在"联邦公报"（FederalRegister(登记、注册)，简称FR）中发表与公布的一般性和永久性规则的集成，具有普遍适用性和法律效应。因此，CFR的内容覆盖广泛。读者在使用CFR时需要注意的是，美国联邦法律在为CFR中的法规提供权威性的同时，对CFR也设置了一定的限制条件。这意味着CFR任何主题下的法规都应当与美国法典（U.S.C.，United States Code，为ACT的一些编纂，可从GPO的网站查询）中具有紧密联系的相应部分一起应用。在某些情况下，法庭可以因为CFR的某法规与联邦法律发生冲突而认定其无效。', color: '#CC9933'},
    {list: 37, abb: 'cGMP', translation: 'Current Good Manufacture Practices', paraphrase: '现行药品生产质量管理规范', definition: 'cGMP指动态药品生产管理规范，英文名 Current Good Manufacture Practices的缩写，也译作现行药品生产管理规范。它要求在产品生产和物流的全过程都必须验证，cGMP是国际药品生产管理标准。\n所谓动态药品生产管理规范，就是强调现场管理（Current），cGMP的内容特别是在对现场工作部分的规范并没有深奥的学问，但是一旦将cGMP规范落实到工作中，执行起来并不简单。\ncGMP的主要目的是为了保证稳定的产品质量，药品质量就是cGMP的核心，而实现这一目标的过程（或理解为现场）是最重要的。', color: '#CC99CC'},
    {list: 38, abb: 'ChP', translation: 'Chinese Pharmacopeia', paraphrase: '中华人民共和国药典', definition: '《中华人民共和国药典》（简称《中国药典》）2015年版，药典包括凡例、正文及通则（本版药典对各部药典共性附录进行整合，将原附录更名为通则），是药品研制、生产、经营、使用和监督管理等均应遵循的法定依据。所有国家药品标准应当符合中国药典凡例及附录的相关要求。\n新版药典进一步扩大药品品种的收载和修订，共收载品种5608种。一部收载品种2598种，其中新增品种440种。二部收载品种2603种，其中新增品种492种。三部收载品种137种，其中新增品种13种、修订品种105种。首次将上版药典附录整合为通则，并与药用辅料单独成卷作为新版药典四部。四部收载通则总数317个，其中制剂通则38个、检测方法240个、指导原则30个、标准物质和对照品相关通则9个；药用辅料收载270种，其中新增137种、修订97种。', color: '#FFCC99'},
    {list: 39, abb: 'CHW', translation: 'Chilled Water', paraphrase: '冷却水', definition: '-', color: '#CC99CC'},
    {list: 40, abb: 'CI', translation: 'Confidence Interval', paraphrase: '置信区间', definition: '置信区间是指由样本统计量所构造的总体参数的估计区间。在统计学中，一个概率样本的置信区间（Confidence interval）是对这个样本的某个总体参数的区间估计。置信区间展现的是这个参数的真实值有一定概率落在测量结果的周围的程度，其给出的是被测量参数的测量值的可信程度，即前面所要求的“一个概率”。', color: '#FFCC99'},
    {list: 41, abb: 'CIP', translation: 'Cleaning In Place', paraphrase: '在位清洗', definition: 'CIP在位清洗系统俗称就地清洗系统简称CIP，又称清洗定位或定位清洗（cleaning in place）。就地清洗是指不用拆开或移动装置，即采用高温、高浓度的洗净液，对设备装置加以强力作用，把与食品的接触面洗净,对卫生级别要求较严格的生产设备的清洗、净化。', color: '#99CC99'},
    {list: 42, abb: 'CM', translation: 'Corrective Maintenance', paraphrase: '纠正性维护', definition: '-', color: '#CC9933'},
    {list: 43, abb: 'CMC', translation: 'Chemical,Manufacturing And Control', paraphrase: '药品的化学、制造和控制', definition: '药品的化学、制造和控制，简称CMC，主要是生产工艺、杂质研究、质量研究，稳定性研究等药学研究资料，是药品申报资料中非常重要的部分。CMC是产品成功开发并注册上市的关键要素之一。', color: '#009999'},
    {list: 44, abb: 'CNC', translation: 'Controlled Non-Classified Area', paraphrase: '受控非洁净区', definition: '-', color: '#999999'},
    {list: 45, abb: 'CoC', translation: 'Certificate Of Compliance', paraphrase: '符合标准证书 ', definition: '-', color: '#CCFF00'},
    {list: 46, abb: 'CPP', translation: 'Critical Process Parameter', paraphrase: '质量关键工艺参数', definition: '工艺参数是指在完成某项工作的工艺的一系列基础数据或者指标，也就是说这些基础参数构成了工艺操作或者设计的内容。质量关键工艺参数是控制质量的关键工艺参数。', color: '#CCFFCC'},
    {list: 47, abb: 'CPU', translation: 'Central Processing Unit', paraphrase: '中央处理单元', definition: '中央处理器（central processing unit，CPU）作为计算机系统的运算和控制核心，是信息处理、程序运行的最终执行单元。CPU自产生以来，在逻辑结构、运行效率以及功能外延上取得了巨大发展。', color: '#99CCFF'},
    {list: 48, abb: 'CQA', translation: 'Critical Quality Attribute', paraphrase: '关键质量属性', definition: '关键质量属性指物质（药品或活性成分）具备的直接或间接影响物质安全、鉴别、强度、纯度的物理，化学，微生物方面特性。关键质量属性确定的标准是基于药品在不符合该质量属性时对患者所造成危害（安全性和有效性）的严重程度。', color: '#CCCCCC'},
    {list: 49, abb: 'CS', translation: 'Control Strategy/Clean Steam', paraphrase: '控制策略/洁净蒸汽', definition: '控制策略是对某一系统或仪器进行控制的策略和方法。换电站主动控制策略由 2 部分组成，一为换电站在架空线路和电缆线路配电网中的故障判别与应对策略，二为配电网故障情况下换电站中所有充放电机的协调控制策略。直流偏差斜率控制策略利用直流 偏差控制策略的偏差特性，利用直流 斜率控制策略的斜率特性，加快了其响能力。', color: '#CC9933'},
    {list: 50, abb: 'CSV', translation: 'Computerized System Verification', paraphrase: '计算机化系统验证', definition: '计算机化系统验证是为确保计算机化系统持续稳定运行既定功能而执行的一项保障措施。范围包括了应用程序系统、与设备关联的计算机化控制系统（设备类系统）以及IT基础设施系统的确认、采购、验证/再验证、使用和维护。', color: '#6699CC'},
    {list: 51, abb: 'CV', translation: 'Column Volume/Cleaning Validation', paraphrase: '柱体积/清洁验证', definition: '柱体积是指凝胶装柱后，从柱的底板到凝胶沉积表面的体积。\n通过对淋洗水的取样进行检测一些项目用于验证清洁效果', color: '#009966'},
    {list: 52, abb: 'DCS', translation: 'Data Communication System/Distributed Control System', paraphrase: '数据传输系统/集散控制系统', definition: '分散控制系统是以微处理器为基础，采用控制功能分散、显示操作集中、兼顾分而自治和综合协调的设计原则的新一代仪表控制系统。集散控制系统简称DCS，也可直译为“分散控制系统”或“分布式计算机控制系统”。\n它采用控制分散、操作和管理集中的基本设计思想，采用多层分级、合作自治的结构形式。其主要特征是它的集中管理和分散控制。目前DCS在电力、冶金、石化等各行各业都获得了极其广泛的应用。', color: '#99CCFF'},
    {list: 53, abb: 'DHT', translation: 'Dirty Hold Time', paraphrase: '污染保持时间', definition: '-', color: '#6699CC'},
    {list: 54, abb: 'DI', translation: 'Digital Input', paraphrase: '数字式输入', definition: '以数字形式输入内容\n存储在数据库中的所有数据值均正确的状态。如果数据库中存储有不正确的数据值，则该数据库称为已丧失数据完整性。数据完整性（Data Integrity）是指数据的精确性（Accuracy） 和可靠性（Reliability）。', color: '#FFFFCC'},
    {list: 55, abb: 'DLI', translation: 'Dynamic Lifetime Indicator', paraphrase: '动态使用寿命指示仪', definition: '实时估算传感器的剩余使用寿命， 通过当前和历史测量数据、 校准值等， 采用一种独特的算法来计算 pH 电极的剩余使用寿命。', color: '#CC9999'},
    {list: 56, abb: 'DO', translation: 'Digital Output', paraphrase: '数字式输出', definition: '以数字形式输出内容', color: '#CC9999'},
    {list: 57, abb: 'DOE', translation: 'Design Of Experiments', paraphrase: '实验设计', definition: '实验设计是指一种有计划的研究，包括一系列有意图性的对过程要素进行改变与其效果观测，对这些结果进行统计分析以便确定过程变异之间的关系，从而改变这过程。', color: '#CCFF00'},
    {list: 58, abb: 'DP', translation: 'Drug Product', paraphrase: '成品药', definition: '-', color: '#CCFFFF'},
    {list: 59, abb: 'DQ', translation: 'Design Qualification', paraphrase: '设计确认', definition: '设计确认（DQ）是新的或改造的厂房、设施、设备验证工作的第一步，内容主要包括为了确认设施、系统和设备的设计方案符合期望目标所做的各种查证', color: '#FFFF00'},
    {list: 60, abb: 'DS', translation: 'Drug Substance', paraphrase: '原液', definition: '原液一词最早来源工业制造中，用于描述某种工业原料浓缩液体的母体，原液的成分单一、浓度更高、配方更精简。', color: '#FFFF00'},
    {list: 61, abb: 'E-DOC', translation: 'Electronic Document System', paraphrase: '电子文档系统', definition: '用于电子文档版本控制、方便文件审批、查阅、培训考核', color: '#FF9933'},
    {list: 62, abb: 'EHS', translation: 'Environment , Health, Safety ', paraphrase: '环境、健康、安全', definition: 'EHS管理体系(environment环境,health健康,safety安全)是指建立环境,安全,健康的组织机构及其职责,程序,过程和资源等构成的整体,是三位一体的管理体系。通过人和程序将公司的EHS方针,合法要求,经营策略与公司的一系列要求联结在一起,实现与公司EHS方针相符的整体EHS业绩的持续改进。由于生产安全,环境保护和职业健康在管理原则和效果上彼此相似,企业的管理,归根结底是对人的管理。可持续发展是企业运用EHS管理时,既要考虑当前发展的需要,又要考虑未来发展的需要。', color: '#CCFF66'},
    {list: 63, abb: 'EM', translation: 'Equipment Module/Environmental Monitoring', paraphrase: '设备模块/环境监测', definition: '模块,又称构件,是能够单独命名并独立地完成一定功能的集合,设备模块则是能够完成系统一定功能的设备集合。', color: '#CC99CC'},
    {list: 64, abb: 'EMPQ', translation: 'Environmental Monitoring Process Qualification', paraphrase: '环境监控表现验证 ', definition: '-', color: '#009966'},
    {list: 65, abb: 'EMS', translation: 'Environment Monitoring System', paraphrase: '环境监测系统', definition: '机房环境监控系统是一个综合利用计算机网络技术、数据库技术、通信技术、自动控制技术、新型传感技术等构成的计算机网络，提供的一种以计算机技术为基础、基于集中管理监控模式的自动化、智能化和高效率的技术手段，系统监控对象主要是机房动力和环境设备等设备（如：配电、UPS、空调、温湿度、漏水、烟雾、视频、门禁、防雷、消防系统等）。', color: '#99CCCC'},
    {list: 66, abb: 'ENG', translation: 'Engineering Station', paraphrase: '工程师站', definition: '-', color: '#FFCC99'},
    {list: 67, abb: 'EP', translation: 'Electro Polishing', paraphrase: '电解抛光', definition: '以金属工件为阳极，在适宜的电解液中进行电解，有选择地除去其粗糙面，提高表面光洁程度的技术，又称电解抛光。电抛光可增加不锈钢的耐腐蚀性，减少电气接触点的电阻，制备金相磨片，提高照明灯具的反光性能，提高各种量具的精度，美化金属日用品和工艺品等，适用于钢铁、铝、铜、镍及各种合金的抛光。', color: '#FF6666'},
    {list: 68, abb: 'EPH', translation: 'Equipment Phase', paraphrase: '基础功能', definition: '价值工程对象之所以存在或必需的用途。', color: '#FF9933'},
    {list: 69, abb: 'EU', translation: 'European Union', paraphrase: '欧盟', definition: '欧洲联盟（德语：Europäische Union，法语：Union européenne），简称欧盟（EU），总部设在比利时首都布鲁塞尔（Brussels），是由欧洲共同体发展而来的，创始成员国有6个，分别为德国、法国、意大利、荷兰、比利时和卢森堡。现拥有27个会员国，正式官方语言有24种。', color: '#009999'},
    {list: 70, abb: 'FAT', translation: 'Factory Acceptance Test ', paraphrase: '工厂验收测试', definition: '工厂验收测试（FAT）是一个过程，通过验证设备是否按照设计规格制造和运行来评估设备在组装过程中和组装之后的过程。 FAT确保组件和控件根据设备本身的功能正常工作。顾名思义，该测试是在工厂执行的。进行FAT通常是为了评估任何差异和不合格之处，并制定处理方式。在测试过程中观察到的偏差或异常会记录在问题报告中，并在发货前进行纠正。', color: '#FFFFCC'},
    {list: 71, abb: 'FDA', translation: 'Food And Drug Administration', paraphrase: '美国食品药品监督管理局\n', definition: 'FDA是食品药品监督管理局（Food and Drug Administration）的简称。FDA有时也代表美国食品药品监督管理局。FDA由美国国会即联邦政府授权，是专门从事食品与药品管理的最高执法机关，也是一个由医生、律师、微生物学家、化学家和统计学家等专业人士组成的致力于保护、促进和提高国民健康的政府卫生管制的监控机构。其它许多国家都通过寻求和接收 FDA 的帮助来促进并监控其本国产品的安全。', color: '#999999'},
    {list: 72, abb: 'FDS', translation: 'Functional Design Specification', paraphrase: '功能设计说明', definition: '-', color: '#CCFF66'},
    {list: 73, abb: 'FFF', translation: 'Formulation, Fill & Finish', paraphrase: '制剂，灌装部门', definition: '-', color: '#FFFFCC'},
    {list: 74, abb: 'FMEA', translation: 'Failure Modes & Effects Analysis', paraphrase: '失败模式和影响分析', definition: '在产品设计阶段和过程设计阶段，对构成产品的子系统、零件，对构成过程的各个工序逐一进行分析，找出所有潜在的失效模式，并分析其可能的后果，从而预先采取必要的措施，以提高产品的质量和可靠性的一种系统化的活动。', color: '#FFCC99'},
    {list: 75, abb: 'FRA', translation: 'Functional Risk Assessment', paraphrase: '功能风险评估', definition: '在风险事件发生之前或之后（但还没有结束），设备的功能能否满足工艺要求或功能是否会对工艺造成的影响的可能性进行量化评估的工作。即，测评设备功能带来的影响的可能程度。', color: '#99CC99'},
    {list: 76, abb: 'FS', translation: 'Functional Specification', paraphrase: '功能说明', definition: '对设备的各功能进行描述，包括功能的运行逻辑，运行参数等。', color: '#FF9999'},
    {list: 77, abb: 'FTP', translation: 'Factory Acceptance Test Protocol', paraphrase: '工厂验收测试方案', definition: '-', color: '#999999'},
    {list: 78, abb: 'FTR', translation: 'Factory Acceptance Test Report', paraphrase: '工厂验收测试报告', definition: '-', color: '#CCCCFF'},
    {list: 79, abb: 'GAMP', translation: 'Good Automated Manufacturing Practice', paraphrase: '良好自动化生产实践指南', definition: '良好自动化生产实践指南,GAMP的第五版题目为’A Risk-base Approach Compliant GxP Computrized Systems‘遵从GXP计算机化系统监管的风险管理方法）；又称GAMP5。国际药物工程协会（ISPE)从确保计算机化系统技能满足预定用途又能符合GXP法规要求出发，组织专家编写一套的简称GAMP的方法性指南文件，该指南从1995年第一版开始到2008年，已经更新出版了5版，所以称为GAMP5。', color: '#99CC99'},
    {list: 80, abb: 'GCP', translation: 'Good Clinical Practices', paraphrase: '药品临床试验管理规范', definition: '为使我国药品临床试验科学、规范，保障受试者的权益，保证药品临床试验的质量，适应我国新药研究开发、参与国际合作和国际竞争的需要，促进我国医药事业的发展，根据《中华人民共和国药品管理法》，参照国际公认的原则，制定本规范。本规范对于药品临床试验的受试者起到保护保障作用，对于申办者、研究者起到监督管理作用，对于试验过程起到规范作用。', color: '#CCCCFF'},
    {list: 81, abb: 'GEP', translation: 'Good Engineering Practice', paraphrase: '良好的工程规范', definition: '-', color: '#99CCFF'},
    {list: 82, abb: 'GMP', translation: 'Good Manufacturing Practice', paraphrase: '药品生产质量管理规范', definition: '药品生产质量管理规范》是药品生产和质量管理的基本准则，适用于药品制剂生产的全过程和原料药生产中影响成品质量的关键工序。大力推行药品GMP，是为了最大限度地避免药品生产过程中的污染和交叉污染，降低各种差错的发生，是提高药品质量的重要措施。', color: '#99CCFF'},
    {list: 83, abb: 'GPP', translation: 'General Process Parameter ', paraphrase: '一般工艺参数', definition: '-', color: '#FFFFCC'},
    {list: 84, abb: 'GQAAC', translation: 'Global Quality Auditing And Compliance', paraphrase: '全球质量审核与合规', definition: '-', color: '#CC99CC'},
    {list: 85, abb: 'GS', translation: 'General Specification', paraphrase: '一般说明', definition: '-', color: '#FF9966'},
    {list: 86, abb: 'HCP', translation: 'Host Cell Protein', paraphrase: '宿主细胞蛋白', definition: '受体细胞也叫宿主细胞。受体细胞有原核受体细胞(最主要是大肠杆菌)、真核受体细胞(最主要是酵母菌)、动物细胞和昆虫细胞(其实也是真核受体细胞)。原核受体细胞中,最常用的宿主细胞是大肠杆菌。', color: '#99CCCC'},
    {list: 87, abb: 'HDS', translation: 'Hardware Design Specification', paraphrase: '硬件设计说明', definition: '-', color: '#CCCCFF'},
    {list: 88, abb: 'HIC', translation: 'Hydrophobic Interaction Chromatography', paraphrase: '疏水层析', definition: '疏水层析也称疏水作用下层析（hydrophobic interaction chromatography HIC）从分离纯化生命物质的机制来看，也属于吸附层析一类。疏水层析和反相层析（reversed phase chromatography）分离生命物质的依据是一致的，利用固定相载体上偶联的疏水性配基与流动相中的一些疏水分子发生可逆性结合而进行分离。该方法基于的是蛋白质的疏水差异，在高盐溶液中，蛋白质会与疏水配基相结合，而其他的杂蛋白则没有此种性质，利用此种性质，可以将蛋白质初步的分离，用于盐析之后的蛋白质进一步提纯。', color: '#CCFFCC'},
    {list: 89, abb: 'HMI', translation: 'Human Machine Interface', paraphrase: '人机交互界面', definition: '人机交互界面是指人与计算机系统之间的通信媒体或手段，是人与计算机之间进行各种符号和动作的双向信息交换的平台。', color: '#FFFFCC'},
    {list: 90, abb: 'HW', translation: 'Hardware', paraphrase: '硬件', definition: '-', color: '#CCCC00'},
    {list: 91, abb: 'I/O', translation: 'Input/Output ', paraphrase: '输入/输出', definition: '输入输出设备（IO设备），是数据处理系统的关键外部设备之一，可以和计算机本体进行交互使用。如：键盘、写字板、麦克风、音响、显示器等。因此输入输出设备起了人与机器之间进行联系的作用。', color: '#CCCC00'},
    {list: 92, abb: 'ICH', translation: 'International Council for Harmonisation of Technical Requirements for Pharmaceuticals for Human Use', paraphrase: '人用药品注册技术要求国际协调会议', definition: '-', color: '#FF6666'},
    {list: 93, abb: 'IEC', translation: 'International Electrotechnical Commission', paraphrase: '国际电工委员会', definition: '国际电工委员会（IEC）成立于1906年，它是世界上成立最早的国际性电工标准化机构，负责有关电气工程和电子工程领域中的国际标准化工作。国际电工委员会的总部最初位于伦敦，1948年搬到了位于日内瓦的现总部处。1887-1900年召开的6次国际电工会议上，与会专家一致认为有必要建立一个永久性的国际电工标准化机构，以解决用电安全和电工产品标准化问题。1904年在美国圣路易召开的国际电工会议上通过了关于建立永久性机构的决议。1906年6月，13个国家的代表集会伦敦，起草了IEC章程和议事规则，正式成立了国际电工委员会。1947年作为一个电工部门并入国际标准化组织（ISO），1976年又从ISO中分立出来。宗旨是促进电工、电子和相关技术领域有关电工标准化等所有问题上（如标准的合格评定）的国际合作。该委员会的目标是：有效满足全球市场的需求；保证在全球范围内优先并最大程度地使用其标准和合格评定计划；评定并提高其标准所涉及的产品质量和服务质量；为共同使用复杂系统创造条件；提高工业化进程的有效性；提高人类健康和安全；保护环境。', color: '#009999'},
    {list: 94, abb: 'IND', translation: 'Investigational New Drug', paraphrase: '新药研究申请', definition: 'IND主要目的是提供足够信息来证明药品在人体进行试验是安全的，以及证明针对研究目的的临床方案设计是合理的。IND主要包括Ⅰ、Ⅱ、Ⅲ期临床试验申请，其中Ⅰ、Ⅱ期临床试验为初期临床试验，是疗效的探索阶段；Ⅲ期临床试验为扩大临床试验，是疗效的验证性阶段，只有在初期临床试验IND获准后，申请人才可以提交扩大临床试验申请。\n在IND申报阶段，FDA一般规定（最低限度）药品申办者必须：（1）做该药的药理研究；（2）在至少二种动物身上进行急毒试验；（3）按照该药预想的用途进行为期二个星期至三个月的短期研究。一旦临床前研究结束，动物试验并没有结束随之完成，许多时间更长、更专项的研究如慢性、抗癌试验将在整个新药申请过程中进行。\n临床前研究用来评估: （1）药品的药理学现象和作用机理(MOA)；（2）药物毒性特征和毒性靶器官；（3）药物吸收、分布、代谢和排泄(ADME)。当药品申办者认为它已具有足够的数据证明该药是安全时，就可准备向FDA提交新药临床研究申请（IND）。本质上IND只是一个建议，通过这 个建议，药品申办者获得FDA的许可，开始在人身上进行试验。', color: '#CCCC00'},
    {list: 95, abb: 'IPC', translation: 'In-Process Control ', paraphrase: '过程控制', definition: '工业中的过程控制是指以温度、压力、流量、液位和成分等工艺参数作为被控变量的自动控制。过程控制也称实时控制，是计算机及时的采集检测数据，按最佳值迅速地对控制对象进行自动控制和自动调节，如数控机床和生产流水线的控制等。', color: '#CCFFFF'},
    {list: 96, abb: 'IPM', translation: 'In-Process Monitoring', paraphrase: '工艺监控', definition: '-', color: '#CC9999'},
    {list: 97, abb: 'IPT', translation: 'In-Process Testing ', paraphrase: '中间测试 ', definition: '-', color: '#CCCC00'},
    {list: 98, abb: 'IQ', translation: 'Installation Qualification ', paraphrase: '安装确认', definition: '安装确认(IQ)是指有客观证据支持,即正确地考虑到所有符合厂商规格的过程设备和辅助安装系统的主要布置和设备供应商的说明。', color: '#FF6666'},
    {list: 99, abb: 'ISPE', translation: 'International Society For Pharmaceutical Engineering', paraphrase: '\n国际制药工程协会\n', definition: '国际制药工程协会（ISPE）是一个制药工程领域的民间组织。1980年在美国佛罗里达州坦帕市成立，主要由制药生产和研发领域的专业人员组成。', color: '#FFFFCC'},
    {list: 100, abb: 'IVI', translation: 'Installation Verification Instruction', paraphrase: '（软件）安装确认说明', definition: '-', color: '#CC9933'},
    {list: 101, abb: 'KPP', translation: 'Key Process Parameter', paraphrase: '主要工艺参数', definition: '-', color: '#CC9999'},
    {list: 102, abb: 'LAN', translation: 'Local Area Network', paraphrase: '局域网', definition: '-', color: '#FFFF00'},
    {list: 103, abb: 'LMH', translation: 'Liter/(Meter)2/Hour', paraphrase: '通量单位：升每平方米每小时', definition: '在流体运动中，单位时间内流经某单位面积的某属性量，是表示某属性量输送强度的物理量。在大气科学中，包含动量通量、热通量、物质通量和水通量。', color: '#CCCC00'},
    {list: 104, abb: 'LODE', translation: 'Lack Of Drug Effect', paraphrase: '药物无效', definition: '-', color: '#CCCC33'},
    {list: 105, abb: 'MCB', translation: 'Master Cell Bank', paraphrase: '主细胞库', definition: '-', color: '#CCFF66'},
    {list: 106, abb: 'MCC', translation: 'Motor Control Center ', paraphrase: '马达控制中心', definition: '电机控制中心统一管理配电和仪器设备，将各种电机控制单元、馈电线接头单元、配电变压器、照明配电盘、联锁继电器以及计量设备装入一个整体安装的机壳内并且由一个公共的封闭母线供电。', color: '#CCCC00'},
    {list: 107, abb: 'MES', translation: 'Manufacturing Execution System', paraphrase: '制造执行系统', definition: '制造执行系统 (MES) 是一个信息系统，它连接、监控和控制复杂的制造系统，工厂车间的数据流与整个组织和供应链中的其他系统集成：\n1.监控和强制执行生产过程的正确执行\n2.监控和控制生产过程中使用的材料\n3.收集生产过程信息\n4.提供数据分析工具', color: '#FF9999'},
    {list: 108, abb: 'MFG', translation: 'Manufacturing', paraphrase: '生产（部）', definition: '生产部又称制造部，是以产品生产为主要工作的部门。', color: '#CCCCCC'},
    {list: 109, abb: 'MHV', translation: 'Membrane Hold Volume', paraphrase: '膜包死体积', definition: '-', color: '#FFFFCC'},
    {list: 110, abb: 'MP', translation: 'Mechanical Polishing', paraphrase: '机械抛光', definition: '机械抛光是依靠非常细小的抛光粉的磨削、滚压作用，除去试样磨面上的极薄一层金属。抛光常常用于增强产品的外观，防止仪器的污染，除去氧化，创建一个反射表面，或防止腐蚀的管道。在冶金中，抛光用于形成平坦，无缺陷的表面，用于在显微镜下检查金属的微观结构。抛光过程中可以使用硅基抛光垫或金刚石溶液。 抛光不锈钢也可以增加不锈钢的清洁卫生程度。', color: '#99CC99'},
    {list: 111, abb: 'MPTR', translation: 'Manufacturing Process Transfer Report', paraphrase: '生产过程转移报告', definition: '-', color: '#FF9966'},
    {list: 112, abb: 'MST', translation: 'Manufacturing Science And Technology', paraphrase: '生产科学技术（组）', definition: '科学解决理论问题，技术解决实际问题。为生产部生产过程提供技术支持。', color: '#99CCCC'},
    {list: 113, abb: 'N/A', translation: 'Not Applicable ', paraphrase: '不适用', definition: '-', color: '#CCCC33'},
    {list: 114, abb: 'NAI', translation: 'No Action Indicated', paraphrase: '无需采取整改', definition: 'NAI表示在FDA工厂审查时，没有开出任何书面形式的不符合项，也可称为“零483”。(FDA的不合格报告表单的编号为483，FDA也将不符合简称“483”)', color: '#CC9999'},
    {list: 115, abb: 'NC', translation: 'Non-Classified Area', paraphrase: '非洁净区', definition: '-', color: '#99CCFF'},
    {list: 116, abb: 'NDA', translation: 'New Drug Application', paraphrase: '新药上市申请', definition: '当人体试验第三阶段完成，所需非临床试验已告结束，则可以出具一套资料，向FNS申请新药上市许可之核准，NDA主要目的是确保上市药品安全有效和质量可控。以植物药NDA为例，FDA认为除其在质量标准方面与化学药品确有不同之外，在安全性和有效性方面二者应符合相同上市标准。因此FND对植物药NDA在安全性和有效性方面的审批要求与相同适应证的化学药品相同，但在质量标准方面可有所不同。\n植物药NDA申报材料与化学药品类似，主要包括以下内容：CMC数据、非临床药理和毒理数据、人体药代动力学和生物利用度数据、微生物数据、临床数据、安全性数据更新报告、统计学数据、病例报告表、有关专利情况、样品、包装及标签等。', color: '#CCFFCC'},
    {list: 117, abb: 'NMPA', translation: 'National Medical Products Administration', paraphrase: '国家药品监督管理局', definition: '组建国家市场监督管理总局。改革市场监管体系，实行统一的市场监管，是建立统一开放竞争有序的现代市场体系的关键环节。为完善市场监管体制，推动实施质量强国战略，营造诚实守信、公平竞争的市场环境，进一步推进市场监管综合执法、加强产品质量安全监管，让人民群众买得放心、用得放心、吃得放心，方案提出，将国家工商行政管理总局的职责，国家质量监督检验检疫总局的职责，国家食品药品监督管理总局的职责，国家发展和改革委员会的价格监督检查与反垄断执法职责，商务部的经营者集中反垄断执法以及国务院反垄断委员会办公室等职责整合，组建国家市场监督管理总局，作为国务院直属机构。其主要职责是，负责市场综合监督管理，统一登记市场主体并建立信息公示和共享机制，组织市场监管综合执法工作，承担反垄断统一执法，规范和维护市场秩序，组织实施质量强国战略，负责工业产品质量安全、食品安全、特种设备安全监管，统一管理计量标准、检验检测、认证认可工作等。', color: '#CCCC00'},
    {list: 118, abb: 'NOR', translation: 'Normal Operation Range', paraphrase: '操作范围', definition: '-', color: '#FF9966'},
    {list: 119, abb: 'NPI', translation: 'New Product Introduction', paraphrase: '新产品引入（需要做风险评估）', definition: '-', color: '#FF9999'},
    {list: 120, abb: 'NWP', translation: 'Normalized Water Permeability', paraphrase: '标准水通量', definition: '-', color: '#009999'},
    {list: 121, abb: 'OAI', translation: 'Official Action Indicated', paraphrase: '强制采取整改', definition: '-', color: '#99CC99'},
    {list: 122, abb: 'OL', translation: 'Optical Length', paraphrase: '光程', definition: '-', color: '#CCFF66'},
    {list: 123, abb: 'OOS', translation: 'Out Of Specification', paraphrase: '检验结果偏差', definition: '-', color: '#999999'},
    {list: 124, abb: 'OP', translation: 'Operations', paraphrase: '操作程序', definition: '-', color: '#CC9933'},
    {list: 125, abb: 'OQ', translation: 'Operational Qualification', paraphrase: '运行确认', definition: '运行确认(OQ)是通过按草拟的SOP运行空载实验,检查和测试仪器设备运行、操作和控制性能,通过记录并以文件形式证实仪器设备符合实验室检验的要求。', color: '#33CC99'},
    {list: 126, abb: 'P&ID', translation: 'Piping and Instrumentation Diagram', paraphrase: '工艺和仪表流程图', definition: 'P&ID 的表达重点是管道的流程以及过程工艺如何控制，显示管道系统是如何将工业加工设备连接在一起的。P&ID 示意图还会显示用于监控物料在管道中的流动情况的仪表和阀门。', color: '#CC9933'},
    {list: 127, abb: 'PA', translation: 'Process Air', paraphrase: '工艺压缩空气', definition: '-', color: '#FF9966'},
    {list: 128, abb: 'PAI', translation: 'Pre Approval Inspection', paraphrase: '批准前检查', definition: '-', color: '#99CCFF'},
    {list: 129, abb: 'PAO', translation: 'Poly Alpha Olefins', paraphrase: '聚α- 烯烃', definition: '-', color: '#CC99CC'},
    {list: 130, abb: 'PAR', translation: 'Proven Acceptable Range', paraphrase: '可接受范围', definition: '-', color: '#9999CC'},
    {list: 131, abb: 'PAS', translation: 'Process Automation System ', paraphrase: '过程自动化系统', definition: '-', color: '#CC9999'},
    {list: 132, abb: 'PAT', translation: 'Process Analytical Technology', paraphrase: '过程分析技术', definition: '是以实时监测（例如在加工中）原材料、中间体和过程的关键质量和性能特征为手段，建立起来的一种设计、分析和控制生产的系统。', color: '#CCCC00'},
    {list: 133, abb: 'PC', translation: 'Process Characteristics/Product Compliant/Personal Computer', paraphrase: '工艺特性研究/产品投诉/ 个人电脑', definition: '-', color: '#FFCCCC'},
    {list: 134, abb: 'PCS', translation: 'Process Control System', paraphrase: '过程控制系统', definition: '以保证生产过程的参量为被控制量使之接近给定值或保持在给定范围内的自动控制系统。这里“过程”是指在生产装置或设备中进行的物质和能量的相互作用和转换过程。表征过程的主要参量有温度、压力、流量、液位、成分、浓度等。通过对过程参量的控制，可使生产过程中产品的产量增加、质量提高和能耗减少。一般的过程控制系统通常采用反馈控制的形式，这是过程控制的主要方式。', color: '#009966'},
    {list: 135, abb: 'PD', translation: 'Process Development', paraphrase: '工艺开发', definition: '-', color: '#FFFF00'},
    {list: 136, abb: 'PDA', translation: 'Parenteral Drug Association', paraphrase: '美国注射剂协会', definition: '美国注射剂协会（PDA）是全球领先的科学，技术和监管信息的促进者。 PDA提高了对制药和生物制药界面临的重要问题的认识和理解，并为社区提供教育。 PDA成立于1946年，作为一个非营利组织，致力于开发科学健全，实用的技术信息和专业知识，以推进制药/生物制药制造科学和监管，使会员可以更好地为患者服务。', color: '#99CCFF'},
    {list: 137, abb: 'PFD', translation: 'Process Flow Diagram', paraphrase: '工艺流程图', definition: '工艺流程图主要利用图形符号的表达方式，能够十分清晰明了的表达工艺流程中各部分原件的结构以及工艺的运行过程。', color: '#CCCC00'},
    {list: 138, abb: 'PHS', translation: 'Public Health Service', paraphrase: '公共健康服务', definition: '-', color: '#FFCC99'},
    {list: 139, abb: 'PLC', translation: 'Programmable Logic Controller', paraphrase: '可编程逻辑控制器', definition: '可编程逻辑控制器是种专门为在工业环境下应用而设计的数字运算操作电子系统。它采用一种可编程的存储器，在其内部存储执行逻辑运算、顺序控制、定时、计数和算术运算等操作的指令，通过数字式或模拟式的输入输出来控制各种类型的机械设备或生产过程。', color: '#009966'},
    {list: 140, abb: 'PM', translation: 'Preventive Maintenance', paraphrase: '预防性维护', definition: '-', color: '#99CCFF'},
    {list: 141, abb: 'PPCS', translation: ' Production Protection Control System', paraphrase: '生产保护控制系统', definition: '-', color: '#CC9933'},
    {list: 142, abb: 'PPE', translation: 'Personal Protective Equipment', paraphrase: '个人防护设备', definition: '-', color: '#99CCFF'},
    {list: 143, abb: 'PPQ', translation: 'Process Performance Qualification', paraphrase: '工艺表现确认 ', definition: '将实际厂房、设施、设备（已确认）以 及经培训的人员与商业化生产的工艺、控 制程序和原辅料等组合起来，生产商业化 的批次。\n工艺性能确认标志着从产品开发和临床生产转移到日常商业生产。工艺性能确认（PPQ）证明了在商业生产规模下工艺设计的有效性和工艺控制策略的适用性。在日常生产中，系统的监测、控制和操作规程应能及时发现和修正产品周期中潜在的工艺变化。这些，PPQ提供了一定的保障。', color: '#FF9999'},
    {list: 144, abb: 'PQ', translation: 'Performance Qualification', paraphrase: '性能确认\n', definition: '性能确认（PQ）是在有制品时，常规正常生产条件下证明设备运行情况能达到预先设定的运行要求。', color: '#CCCCFF'},
    {list: 145, abb: 'PQA', translation: 'Product Quality Attributes', paraphrase: '产品质量属性', definition: '-', color: '#FFFF00'},
    {list: 146, abb: 'PQP', translation: 'Project Quality Plan', paraphrase: '项目质量计划', definition: '项目质量计划是指为确定项目应该达到的质量标准和如何达到这些项目质量标准而做的项目质量的计划与安排。项目质量计划是质量策划的结果之一。它规定与项目相关的质量标准，如何满足这些标准，由谁及何时应使用哪些程序和相关资源。 项目质量计划工作的成果：项目质量计划、项目质量工作说明、质量核检清单、可用于其它管理的信息。', color: '#FFCC99'},
    {list: 147, abb: 'PQS', translation: 'Pharmaceutical Quality System', paraphrase: '药品质量体系', definition: '-', color: '#CCCCFF'},
    {list: 148, abb: 'PR', translation: 'Procedures', paraphrase: '程序', definition: '它以某些程序设计语言编写，运行于某种目标结构体系上。打个比方，程序就如同以英语（程序设计语言）写作的文章，要让一个懂得英语的人（编译器）同时也会阅读这篇文章的人（结构体系）来阅读、理解、标记这篇文章。一般的，以英语文本为基础的计算机程序要经过编译、链接而成为人难以解读，但可轻易被计算机所解读的数字格式，然后放入运行。', color: '#009999'},
    {list: 149, abb: 'PS', translation: 'Pure Steam/Plant Steam', paraphrase: '纯蒸汽/工业蒸汽', definition: '-', color: '#9999CC'},
    {list: 150, abb: 'PV', translation: 'Process Validation', paraphrase: '工艺验证', definition: '能够很好的确保在特定工艺下能够生产出始终如一的符合预定规格和预期质量标准的产品的证明性工作。在这一阶段对已经设计的工艺进行确认，证明其能够进行重复性的商业化生产。', color: '#CCFF00'},
    {list: 151, abb: 'PW', translation: 'Purified Water', paraphrase: '纯水', definition: '纯水是一种无机化合物，化学式为H2O，具有一定结构的液体，虽然它没有刚性，但它比气态水分子的排列有规则得多。在液态水中，水的分子并不是以单个分子形式存在，而是有若干个分子以氢键缔合形成水分子簇( H2O)，因此水分子的取向和运动都将受到周围其他水分子的明显影响。对于水的结构还没有肯定的结构模型，目前被大多数接受的主要有3 种：混合型、填隙式和连续结构(或均匀结构)模型。', color: '#FFFF00'},
    {list: 152, abb: 'Q&A', translation: 'Question And Answer', paraphrase: '问题和解答', definition: '-', color: '#FFFF99'},
    {list: 153, abb: 'QA', translation: 'Quality Assurance', paraphrase: '质量保证', definition: '质量保证（Quality Assurance）也是质量管理的一部分，它致力于提供质量要求会得到满足的信任。质量保证是指为使人们确信产品或服务能满足质量要求而在质量管理体系中实施并根据需要进行证实的全部有计划和有系统的活动。质量保证一般适用于有合同的场合，其主要目的是使用户确信产品或服务能满足规定的质量要求。\n质量保证的内容绝不是单纯的保证质量，保证质量是质量控制的任务，质量保证是以保证质量为其基础，进一步引申到提供“信任”这一基本目的。', color: '#99CCCC'},
    {list: 154, abb: 'QbD', translation: 'Quality By Design', paraphrase: '质量源于设计', definition: '质量源于设计（QbD），主要涉及工艺设计与分析方法验证的QbD研发体系。还对QbD方法的重要工具，如过程分析技术（PAT）、风险评估、实验设计（DoE）、模型与模拟、先前知识与质量体系等，在药品研发中的具体应用以实例进行了叙述。', color: '#CCCC33'},
    {list: 155, abb: 'QC', translation: 'Quality Control', paraphrase: '质量控制', definition: '为达到质量要求所采取的作业技术和活动称为质量控制。这就是说，质量控制是为了通过监视质量形成过程，消除质量环上所有阶段引起不合格或不满意效果的因素。以达到质量要求，获取经济效益，而采用的各种质量作业技术和活动。\n质量控制是为使产品或服务达到质量要求而采取的技术措施和管理措施方面的活动。质量控制的目标在于确保产品或服务质量能满足要求（包括明示的、习惯上隐含的或必须履行的规定）。', color: '#CC99CC'},
    {list: 156, abb: 'QE', translation: 'Quality Engineer', paraphrase: '质量工程师', definition: '-', color: '#FFFFCC'},
    {list: 157, abb: 'QP', translation: 'Quality Policy', paraphrase: '质量政策', definition: '-', color: '#CC9999'},
    {list: 158, abb: 'RA', translation: 'Risk Assessment ', paraphrase: '风险评估', definition: '风险评估（Risk Assessment） 是指，在风险事件发生之前或之后（但还没有结束），该事件给人们的生活、生命、财产等各个方面造成的影响和损失的可能性进行量化评估的工作。即，风险评估就是量化测评某一事件或事物带来的影响或损失的可能程度。', color: '#009966'},
    {list: 159, abb: 'RCB', translation: 'Research Cell Bank ', paraphrase: '研发细胞库', definition: '-', color: '#9999CC'},
    {list: 160, abb: 'RT', translation: 'Resident Time', paraphrase: '停留时间', definition: '-', color: '#FF9966'},
    {list: 161, abb: 'RTM', translation: 'Requirement Traceability Matrix', paraphrase: '需求追溯矩阵', definition: '需求追溯矩阵是一种主要管理需求变更和验证需求是否得到了实现的有效工具，借助RTM，可以跟踪每个需求的状态。', color: '#FFFF99'},
    {list: 162, abb: 'RW', translation: 'Raw Water（Tap Water）', paraphrase: '原水（自来水）', definition: '原水一般是指采集于自然界，包括地下水、山泉水、水库水等自然界中的天然水源，未经过任何人工的净化处理。', color: '#FFFFCC'},
    {list: 163, abb: 'SAE', translation: 'Serious Adverse Event', paraphrase: '严重不良事件', definition: '-', color: '#33CC99'},
    {list: 164, abb: 'SAT', translation: 'Site Acceptance Test ', paraphrase: '现场验收测试', definition: '设备/系统安装后在终端用户场地后，为支持其后续确认/验证或商业化使用而进行的检查、静态和动态测试。现场接收测试应在终端用户现场进行，并由相关部门进行批准。', color: '#669999'},
    {list: 165, abb: 'SCADA', translation: 'Supervisor Control And Data Acquisition', paraphrase: '监测控制和数据采集系统', definition: '它可以实时采集现场数据，对工业现场进行本地或远程的自动控制，对工艺流程进行全面、实时的监视，并为生产、调度和管理提供必要的数据。\nSCADA系统的主要功能包括数据采集、本地和远程控制、多种通讯介质联接、易于重新配置及本地和远程诊断', color: '#99CCCC'},
    {list: 166, abb: 'SD', translation: 'System Description ', paraphrase: '系统描述', definition: '-', color: '#CCCCFF'},
    {list: 167, abb: 'SDS', translation: 'Software Design Specification ', paraphrase: '软件设计说明', definition: '-', color: '#99CC99'},
    {list: 168, abb: 'SEC-HPLC', translation: 'Size Exclusion Chromatography-High-Performance Liquid Chromatography', paraphrase: '凝胶过滤高效液相色谱', definition: '凝胶色谱技术是以多孔凝胶为固定相，利用凝胶孔的空间尺寸效应，使不同大小的分子按照由大到小的洗脱顺序达到分离的高效液相色谱（HPLC）方法，从而达到净化的目的。此外，凝胶色谱还有因为惰性微球表面对有机物吸附小所以柱污染小，以及脱盐等优点。', color: '#FF6666'},
    {list: 169, abb: 'SFC', translation: 'Sequential Function Chart', paraphrase: '顺序功能图', definition: '顺序功能图（SFC，Sequential Function Chart）采用IEC标准的语言，用于编制复杂的顺控程序。又称为状态转移图或功能表图，它是描述控制系统的控制过程、功能和特性的一种图形，也是设计顺序控制程序的工具。利用这种先进的编程方法，初学者也很容易编出复杂的顺控程序，大大提高了工作效率，也为调试、试运行带来许多言传的方便。', color: '#99CCCC'},
    {list: 170, abb: 'SIA', translation: 'System Impact Assessment', paraphrase: '系统影响性评估', definition: '-', color: '#FFCCCC'},
    {list: 171, abb: 'SIP', translation: 'Steam In Place', paraphrase: '在位蒸汽处理', definition: '-', color: '#009966'},
    {list: 172, abb: 'SISPQ', translation: 'Safety, Identity, Strength, Purity, and Quality', paraphrase: '产品质量的安全性、一致性、有效性、纯度和质量', definition: '-', color: '#CC9999'},
    {list: 173, abb: 'SME', translation: 'Subject Matter Expert', paraphrase: '各个区域的技术专家', definition: '-', color: '#FFCCCC'},
    {list: 174, abb: 'SMP', translation: 'Standard Management Procedure', paraphrase: '标准管理规程', definition: '-', color: '#FF9933'},
    {list: 175, abb: 'SN', translation: 'Serial Number', paraphrase: '产品序列号', definition: '产品序列号是指用一个唯一的代码来定义企业生产的每一个产品。这个代码可以根据预定义的编码规则自动生成；也可以手工创建。主要作用在于产品生产进程的控制，生产质量管理，物料库存的追踪，产品售后服务，版权控制等多个方向。利用条码标签打印序列号，并与实际产品结合可以实现企业对产品的各项作用。', color: '#99CC99'},
    {list: 176, abb: 'SOP', translation: 'Standard Operating Procedure', paraphrase: '标准操作规程', definition: '将某一事件的标准操作步骤和要求以统一的格式描述出来,用来指导和规范日常的工作.SOP的精髓,就是将细节进行量化,用更通俗的话来说,SOP就是对某一程序中的关键控制点进行细化和量化。', color: '#FFCCCC'},
    {list: 177, abb: 'SOSC', translation: 'System Overview & System Configuration', paraphrase: '系统概述及系统配置', definition: '-', color: '#009966'},
    {list: 178, abb: 'SS', translation: 'Stainless Steel', paraphrase: '不锈钢 ', definition: '不锈钢（Stainless Steel）是不锈耐酸钢的简称，耐空气、蒸汽、水等弱腐蚀介质或具有不锈性的钢种称为不锈钢；而将耐化学腐蚀介质（酸、碱、盐等化学浸蚀）腐蚀的钢种称为耐酸钢。', color: '#CCFF66'},
    {list: 179, abb: 'SU', translation: 'Single Use', paraphrase: '一次性', definition: '只有一次，不重复的。', color: '#009999'},
    {list: 180, abb: 'SW', translation: 'Softened Water', paraphrase: '软化水', definition: '在日常生活中，我们经常见到水壶用久后内壁会有水垢生成。这是什么原因呢？原来在我们取用的水中含有不少无机盐类物质，如钙、镁盐等。这些盐在常温下的水中肉眼无法发现，一旦它们加温煮沸，便有不少钙、镁盐以碳酸盐形成沉淀出来，它们紧贴壶壁就形成水垢。我们通常把水中钙、镁离子的含量用“硬度”这个指标来表示。硬度1度相当于每升水中含有10毫克氧化钙。低于8度的水称为软水，高于17度的称为硬水，介于8～17度之间的称为中度硬水。雨、雪水、江、河、湖水都是软水，泉水、深井水、海水都是硬水。', color: '#FFFFCC'},
    {list: 181, abb: 'TC', translation: 'Thin Client ', paraphrase: '瘦客户机', definition: '瘦客户机（thin client）是使用专业嵌入式处理器、小型本地DOM电子盘、精简版操作系统的基于PC工业标准设计的小型行业专用商用PC。 配置包含专业的低功耗、高运算功能的嵌入式处理器。不可移除地用于存储操作系统的本地闪存、以及本地系统内存、网络适配器、显卡和其它外设的标配输入/输出选件。瘦客户机没有可移除的部件，可以提供比普通PC更加安全可靠的使用环境，以及更低的功耗，更高的安全性。', color: '#FFCCCC'},
    {list: 182, abb: 'TCU', translation: 'Temperature Control Unit', paraphrase: '温控单元', definition: '-', color: '#FF9966'},
    {list: 183, abb: 'TDM', translation: 'Test And Documentation Matrix', paraphrase: '测试文件矩阵', definition: '-', color: '#33CC99'},
    {list: 184, abb: 'TM', translation: 'Traceability Matrix', paraphrase: '（用户需求）追溯矩阵', definition: '-', color: '#FF9999'},
    {list: 185, abb: 'TMP', translation: 'Transfer Membrane Pressure', paraphrase: '跨膜压力', definition: '跨膜压差被定义为驱动水透过膜所需的压力，为进水压力和过滤压力的差值。孔径较小的膜所需的跨膜压差也较大，在水温较低、通量较高以及发生污染时，跨膜压差也较高。', color: '#999999'},
    {list: 186, abb: 'TOC', translation: 'Total Organic Carbon', paraphrase: '总有机碳', definition: '总有机碳是指水体中溶解性和悬浮性有机物含碳的总量。水中有机物的种类很多，除含碳外，还含有氢、氮、硫等元素，还不能全部进行分离鉴定。常以“TOC”表示。TOC是一个快速检定的综合指标，它以碳的数量表示水中含有机物的总量。但由于它不能反映水中有机物的种类和组成，因而不能反映总量相同的总有机碳所造成的不同污染后果。由于TOC的测定采用燃烧法，因此能将有机物全部氧化，它比生化需氧量（BOD）或化学需氧量（COD）更能直接表示有机物的总量。通常作为评价水体有机物污染程度的重要依据。', color: '#CC9933'},
    {list: 187, abb: 'TPP', translation: 'Target Product Profiles', paraphrase: '产品目标属性', definition: '-', color: '#FF6666'},
    {list: 188, abb: 'TS', translation: 'Technical Specification', paraphrase: '技术规范', definition: '技术规范是对标准化的对象提出技术要求，也就是用于规定标准化对象的能力。', color: '#CCCC00'},
    {list: 189, abb: 'UDS', translation: 'Unit Design Specification ', paraphrase: '系统设计规格书', definition: '-', color: '#FF9966'},
    {list: 190, abb: 'UF', translation: 'Ultrafiltration', paraphrase: '超滤浓缩 ', definition: '溶质被膜截留，水分子穿过膜，溶质得以浓缩的方法。', color: '#FF6666'},
    {list: 191, abb: 'UF/DF', translation: 'Ultrafiltration/Diafiltration ', paraphrase: '超滤/洗滤', definition: '洗滤是样品通过一定孔径的膜,小分子缓冲液能够透过膜而大分子蛋白分子被截留，从而将小分子与生物大分子分开的一种分离纯化技术。再向样品中补加新的缓冲液体系从而达到换液的目的。', color: '#999999'},
    {list: 192, abb: 'UP', translation: 'Unit Procedures', paraphrase: '单位程序', definition: '-', color: '#999999'},
    {list: 193, abb: 'UPB', translation: 'Un-Processed Bulk', paraphrase: '细胞收获液', definition: '-', color: '#CCCCCC'},
    {list: 194, abb: 'UPS', translation: 'Uninterrupted Power Supply', paraphrase: '不间断电源', definition: 'UPS即不间断电源(Uninterruptible Power Supply)，是一种含有储能装置的不间断电源。主要用于给部分对电源稳定性要求较高的设备，提供不间断的电源。\n当市电输入正常时，UPS 将市电稳压后供应给负载使用，此时的UPS就是一台交流式电稳压器，同时它还向机内电池充电；当市电中断（事故停电）时， UPS 立即将电池的直流电能，通过逆变器切换转换的方法向负载继续供应220V交流电，使负载维持正常工作并保护负载软、硬件不受损坏。UPS 设备通常对电压过高或电压过低都能提供保护。', color: '#FF9999'},
    {list: 195, abb: 'URS', translation: 'User Requirement Specification', paraphrase: '用户需求说明书', definition: '指使用方对设备、厂房、硬件设施系统等提出的自己的期望使用需求说明，设计方依据这个需求等提出自己具体的方案，设备供应商依据客户提供的URS方案设计施工。', color: '#009999'},
    {list: 196, abb: 'USP', translation: 'United States Pharmacopoeia', paraphrase: '美国药典', definition: '《美国药典》是由美国药典委员会编写的。美国药典是美国政府对药品质量标准和检定方法作出的技术规定，也是药品生产、使用、管理、检验的法律依据。NF收载了美国药典（USP）尚未收入的新药和新制剂。', color: '#009966'},
    {list: 197, abb: 'UV', translation: 'Ultraviolet', paraphrase: '紫外吸收值', definition: '紫外吸收光谱和可见吸收光谱都属于分子光谱，它们都是由于价电子的跃迁而产生的。利用物质的分子或离子对紫外和可见光的吸收所产生的紫外可见光谱及吸收程度可以对物质的组成、含量和结构进行分析、测定、推断。', color: '#009966'},
    {list: 198, abb: 'VAI', translation: 'Voluntary Action Indicated', paraphrase: '自愿采取整改', definition: '-', color: '#33CC99'},
    {list: 199, abb: 'VF', translation: 'Viral Filtration', paraphrase: '除病毒过滤 ', definition: '-', color: '#FF9966'},
    {list: 200, abb: 'VI', translation: 'Low Ph Viral Inactivation', paraphrase: '低pH病毒灭活 ', definition: '-', color: '#999999'},
    {list: 201, abb: 'VIN', translation: 'Viral Inactivation And Neutralization', paraphrase: '病毒灭活', definition: '-', color: '#CCFF66'},
    {list: 202, abb: 'VM', translation: 'Virtual Machine', paraphrase: '虚拟机', definition: '虚拟机（Virtual Machine）指通过软件模拟的具有完整硬件系统功能的、运行在一个完全隔离环境中的完整计算机系统。在实体计算机中能够完成的工作在虚拟机中都能够实现。在计算机中创建虚拟机时，需要将实体机的部分硬盘和内存容量作为虚拟机的硬盘和内存容量。每个虚拟机都有独立的CMOS、硬盘和操作系统，可以像使用实体机一样对虚拟机进行操作。', color: '#FF9999'},
    {list: 203, abb: 'VMP', translation: 'Validation Master Plan', paraphrase: '验证主计划', definition: '验证总体计划，也称为“ VMP”，概述了设施认证所涉及的原则，定义了要进行认证的区域和系统，并提供了用于实现和维护合格设施的书面计划。 VMP是验证计划的基础，并且应包括过程验证，设施和公用事业资格与验证，设备资格，清洁和计算机验证。这是GMP（药品生产质量管理规范）规范的制药行业的重要文件，因为它推动了验证项目的结构化方法。', color: '#669999'},
    {list: 204, abb: 'VP', translation: 'Validation Plan', paraphrase: '验证计划', definition: '-', color: '#FF9933'},
    {list: 205, abb: 'VSR', translation: 'Validation Summary Report', paraphrase: '验证总结报告', definition: '-', color: '#CCCC33'},
    {list: 206, abb: 'WCB', translation: 'Working Cell Bank ', paraphrase: '工作细胞库', definition: '工作细胞库（Working Cell Bank，WCB）是由有限传代水平的主细胞库制备而来的均一性细胞悬液，分装适宜体积于多个容器中，冻存于-130℃或以下用于生产。由本细胞库移出的细胞无论开瓶与否，均不得再返回贮存。', color: '#CCCC00'},
    {list: 207, abb: 'WC-CPP', translation: 'Well Controlled-Critical Process Parameter ', paraphrase: '可控关键工艺参数', definition: '-', color: '#FF9999'},
    {list: 208, abb: 'WFI', translation: 'Water For Injection', paraphrase: '注射用水', definition: '-', color: '#FF9999'},
    {list: 209, abb: 'WHO', translation: 'World Health Organization', paraphrase: '世界卫生组织', definition: '世界卫生组织是联合国下属的一个专门机构，总部设置在瑞士日内瓦，只有主权国家才能参加，是国际上最大的政府间卫生组织。\n世界卫生组织的宗旨是使全世界人民获得尽可能高水平的健康。世界卫生组织的主要职能包括：促进流行病和地方病的防治；提供和改进公共卫生、疾病医疗和有关事项的教学与训练；推动确定生物制品的国际标准。', color: '#FFFF00'},
]